super::multisig_impl::multisig_impl!(
    burn_checked_multisig_ix_with_program_id,
    burn_checked_multisig_invoke_with_program_id,
    burn_checked_multisig_invoke_signed_with_program_id,
    burn_checked_ix_with_program_id,
    BurnCheckedAccounts,
    BurnCheckedKeys,
    BurnCheckedIxArgs,
    BURN_CHECKED_IX_ACCOUNTS_LEN,
);
