super::multisig_impl::multisig_impl_no_ix_args!(
    close_account_multisig_ix,
    close_account_multisig_invoke,
    close_account_multisig_invoke_signed,
    close_account_multisig_ix_with_program_id,
    close_account_multisig_invoke_with_program_id,
    close_account_multisig_invoke_signed_with_program_id,
    close_account_ix_with_program_id,
    CloseAccountAccounts,
    CloseAccountKeys,
    CLOSE_ACCOUNT_IX_ACCOUNTS_LEN,
);
