super::by_custodian::impl_by_custodian!(
    withdraw_by_custodian_ix,
    withdraw_by_custodian_invoke,
    withdraw_by_custodian_invoke_signed,
    withdraw_ix,
    WithdrawAccounts,
    WithdrawKeys,
    WithdrawIxArgs,
    WITHDRAW_IX_ACCOUNTS_LEN,
);
